### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by Mahikagarg09** [DevFeed404/DevFeed-1.0#103]
FAQ section on landing page having questions such as-
1.What kind of tech events does DevFeed cover?
DevFeed covers a wide range of tech events, including conferences, meetups, workshops, hackathons, webinars, and panel discussions. We strive to provide a comprehensive overview of events that cater to various areas of technology and expertise.

2.How can I stay updated on the latest speakers and topics featured in the newsletter?
Our newsletters will provide you with exclusive updates on the latest speakers and topics for upcoming tech events.

3.Can I share the newsletter with my colleagues or friends?
Absolutely! We encourage you to share DevFeed's newsletter with your colleagues, friends, and anyone else who might be interested in tech events. You can forward the newsletter email directly to them or direct them to our website to subscribe on their own.

4.Does DevFeed cover virtual or online tech events as well?
Absolutely! DevFeed recognizes the growing importance of virtual and online events in the tech industry. We cover a wide range of virtual events, webinars, and online conferences to ensure that you have access to valuable learning and networking opportunities, regardless of your location.

These are the FAQs so far in my mind. If you wish to have FAQ section and have another questions ,please do tell.

Kindly assign this issue to me.

**Comment by tuhinaww** [comment]
Assigning it to you @Mahikagarg09

**Comment by Mahikagarg09** [comment]
Can I work on the frontend part without connecting backend in any way?

**Comment by Mahikagarg09** [comment]
ISSUE RESOLVED
PULL REQUEST- Faq section added #115
kindly review the PR.
