### ISSUE TITLE
Want to change the UI of the "People talk about us" section to a more interactive UI design

### ISSUE THREAD

**Issue by Lobi29** [DevFeed404/DevFeed-1.0#105]
Old design : 
![13](https://github.com/DevFeed404/DevFeed-1.0/assets/108052802/4bf6060c-7313-4de5-83bc-5be87fe95333)

New design : 
![12](https://github.com/DevFeed404/DevFeed-1.0/assets/108052802/ce60cc00-c7a4-48e8-bed7-d0f96993f30e)

I want to change the Old testimonial section to a modern testimonial section which align with the requirements of the website.

Please assign this UI improvement work to me, under @GSSOC2023

**Comment by ayushgupta4002** [comment]
hi @Lobi29 Sorry , we have a duplicate issue and someone else is working on it!
