### ISSUE TITLE
feat: routes for every component

### ISSUE THREAD

**Issue by SINJINI-G** [DevFeed404/DevFeed-1.0#110]
The current structure of the app needs to be modified to implement proper routing. 
I will use React Router to implement this.. This is the second step that is required before issue #30 can be addressed.

Will you please assign this issue to me under gssoc 2023?

@ayushgupta4002 @r3yc0n1c @tuhinaww

**Comment by ayushgupta4002** [comment]
hey @SINJINI-G 
please go ahead best of luck !

**Comment by SINJINI-G** [comment]
Hi @ayushgupta4002 !! Can you please review and merge my PR for this issue so that I can make the PR for issue #30 .
