### ISSUE TITLE
Improvements to website

### ISSUE THREAD

**Issue by codingniket** [DevFeed404/DevFeed-1.0#13]
Wanted to add scroll on top feature as well add few Testimonials for GSSoC 23

**Comment by ayushgupta4002** [comment]
go ahead @codingniket

**Comment by rayyan016** [comment]
Hi @ayushgupta4002 . I would like to give a shot at fixing this issue as well. Could you assign this to me as well under GSSOC'23?

**Comment by codingniket** [comment]
@ayushgupta4002  it is showing Authorization required to deploy.
If you can help with error

**Comment by ayushgupta4002** [comment]
Thankyou Contributors for your time!
