### ISSUE TITLE
Fix README.md for client side start command. {GSSoC '23}

### ISSUE THREAD

**Issue by GVishnudhasan** [DevFeed404/DevFeed-1.0#132]
In the README.md, it has mentioned that `npm run dev` starts the client-side development code.

# Ref:
![Screenshot 1945-03-03 at 6 27 24 PM](https://github.com/DevFeed404/DevFeed-1.0/assets/94748228/f081942b-56dc-468b-a690-db705f8d49ac)

But, package.json in the code suggests that `npm run start` contains the script of `react-scripts start`.

# Ref:
![Screenshot 1945-03-03 at 6 27 06 PM](https://github.com/DevFeed404/DevFeed-1.0/assets/94748228/f501dda0-c01c-47c4-ba1c-37737f46406c)

Please assign this issue to GSSoC '23 so that we could fix it ASAP.

**Comment by Divyansh3021** [comment]
go ahead. @GVishnudhasan
