### ISSUE TITLE
Add "scroll to top" button on home page

### ISSUE THREAD

**Issue by rayyan016** [DevFeed404/DevFeed-1.0#14]
Hi. I would like to add a feature to scroll to top as a button on the home page. Could you please assign me this issue under GSSOC'23?

**Comment by ayushgupta4002** [comment]
Cool @rayyan016 please go ahead ✓

**Comment by ayushgupta4002** [comment]
Hey @rayyan016 
There is a similar issue#13 please comment there,
Will assign you and merge on the basis of first come ;
