### ISSUE TITLE
Missing Issue Template in Repository

### ISSUE THREAD

**Issue by Nishitbaria** [DevFeed404/DevFeed-1.0#144]
**Description:**

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

**Comment by shivaniyuvrajyadav** [comment]
hey @ayushgupta4002 if this is issue is not completed yet i want to work on it . please assign it to me .
