### ISSUE TITLE
Improving the UI of Testimonial Section

### ISSUE THREAD

**Issue by Vishalk91-4** [DevFeed404/DevFeed-1.0#147]
Hi @ayushgupta4002 
The UI of People talk about section is not in the centre and I would like to change the design, such that other than the z-index the colour changes or it differentiates from rest section to make it more noticeable
The Present UI seems to be merged with rest sections

![image](https://github.com/DevFeed404/DevFeed-1.0/assets/116670999/644e9501-bce6-406d-8717-f65111d37f8f)

I can make the necessary changes
Could you please assign it to me under GSSOC23

**Comment by Divyansh3021** [comment]
go ahead @Vishalk91-4 !!

**Comment by Vishalk91-4** [comment]
@Divyansh3021 , actually I was having my end sem exams so couldn't complete the issue, I've thought of adding animation or glasscard type for this , Can you give some time like till Saturday or Sunday
Please don't assign it to someone else
