### ISSUE TITLE
[GSSoC]  the last element of  Frequently Asked Questions overlap with the coming section 

### ISSUE THREAD

**Issue by elhussienalmasri** [DevFeed404/DevFeed-1.0#161]
when the user open the last element of Frequently Asked Questions , it overlap with the coming  section as 
the Screenshot show 
![DevFeed](https://github.com/DevFeed404/DevFeed-1.0/assets/90080237/caf8e378-a3ea-43ab-8f62-31809d489c48)

**Comment by elhussienalmasri** [comment]
please assign this issue for me

**Comment by ayushgupta4002** [comment]
go ahead @elhussienalmasri all the best !
