### ISSUE TITLE
Subscribe border ui enhance 

### ISSUE THREAD

**Issue by Ajay-308** [DevFeed404/DevFeed-1.0#162]
Subscribe button has low border radius due to which button ui is not look more attractive .
giving some extra radius around 9-10 rem will be great.

![WhatsApp Image 2023-05-29 at 2 05 13 PM](https://github.com/DevFeed404/DevFeed-1.0/assets/112794893/fef888a7-d2e8-48fb-bd8e-8577b77d3a8e)

**Comment by Ajay-308** [comment]
pls assign this issue to me

**Comment by ayushgupta4002** [comment]
Go ahead @Ajay-308
