### ISSUE TITLE
The footer section can be improved. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [DevFeed404/DevFeed-1.0#174]
The footer section of the website is very basic and can be made more interesting. I can design a footer through figma and code in into the website.

Current footer section:
![footer is very basic](https://github.com/DevFeed404/DevFeed-1.0/assets/116020663/20a7024e-df84-4a19-a83f-93be92d495f6)

Sample Footer:
![sample footer design](https://github.com/DevFeed404/DevFeed-1.0/assets/116020663/1f283039-617c-4486-b905-6e347c38496e)

**Comment by ayushgupta4002** [comment]
go ahead @1Shubham7 all the best for your contribution

**Comment by 1Shubham7** [comment]
@ayushgupta4002  Thanks a lot. I will surely not disappoint you.
