### ISSUE TITLE
Fix Text in README

### ISSUE THREAD

**Issue by Sriparno08** [DevFeed404/DevFeed-1.0#186]
I have noticed a typo in README.

![Screenshot 2023-06-01 114534](https://github.com/DevFeed404/DevFeed-1.0/assets/89148144/218b4047-57a3-4e3e-910b-a82a178c3ab8)

Fix:

The inverted comma (') after the colon (:) should be removed.

I would like to contribute as part of GSSoC'23.

**Comment by Shayari08** [comment]
can this be assigned to me?
