### ISSUE TITLE
Too Much Space Between FAQ and Footer 

### ISSUE THREAD

**Issue by ayushgupta4002** [DevFeed404/DevFeed-1.0#190]
There is too much space coming between FAQ and Reach Out to us Section.
![image](https://github.com/DevFeed404/DevFeed-1.0/assets/66496371/a0362a2d-c93f-4749-96a9-15a38b26c867)

Desired Output : Reduce the space between them

**Comment by Ajay-308** [comment]
assing this issue to me

**Comment by YashKoli02** [comment]
Assign this issue to me

**Comment by Ajay-308** [comment]
done
