### ISSUE TITLE
Add readme a new look 

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [DevFeed404/DevFeed-1.0#23]
I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

**Comment by Ayush-Tibrewal** [comment]
@rushabhpanbude 
please assign me with the issue

**Comment by rushabhpanbude** [comment]
> @rushabhpanbude please assign me with the issue

I am not the admin

**Comment by Ayush-Tibrewal** [comment]
@ayushgupta4002 @Adi-ty

**Comment by Adi-ty** [comment]
@Ayush-Tibrewal go ahead

**Comment by ayushgupta4002** [comment]
@Ayush-Tibrewal 
we had a recent merge in our readme file so please make sure to take a pull before creating PR

**Comment by Ayush-Tibrewal** [comment]
hii @ayushgupta4002 but it is showing This branch is not behind the upstream DevFeed404:main
No new commits to fetch. Enjoy your day!

**Comment by ayushgupta4002** [comment]
Ohkay!
Please make your PR after you are done
