### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by SINJINI-G** [DevFeed404/DevFeed-1.0#24]
I will re-structure the repository removing the unnecessary files like node_modules through .gitignore

Can you please assign this issue to me for gssoc 2023?? @ayushgupta4002

**Comment by Adi-ty** [comment]
We already have .gitignore file in server to ignore .env

**Comment by SINJINI-G** [comment]
Hello @Adi-ty !!

I just checked the updated file structure and saw that the server's .gitignore does not have the node modules in it due to which the redundant files are still there. 

Can you reopen the issue and assign it to me?

**Comment by Adi-ty** [comment]
@SINJINI-G sure go ahead

**Comment by SINJINI-G** [comment]
Heyy @Adi-ty !!

I have fixed the issue.. waiting for your review..

**Comment by Adi-ty** [comment]
> Heyy @Adi-ty !!
> 
> I have fixed the issue.. waiting for your review..

Thanks @SINJINI-G

**Comment by SINJINI-G** [comment]
Hii @ayushgupta4002 !! Can you please add the level tag to this issue? It helps me a lot to keep track of my work.
