### ISSUE TITLE
[Feature] Scroll to Top Button

### ISSUE THREAD

**Issue by parthpathakpp1** [DevFeed404/DevFeed-1.0#25]
I can add scroll to top button . When somebody will click the button it will automatically navigate the user to top . 
![gssoccc5](https://github.com/DevFeed404/DevFeed-1.0/assets/85991449/65c1fe16-7cd0-4d7c-9862-0817b47203a8)

**Comment by parthpathakpp1** [comment]
assing me this issue . I will make this functionality.

**Comment by ayushgupta4002** [comment]
hi @parthpathakpp1 
there is a similar issue (#13 ) you can look forward to it
