### ISSUE TITLE
Enable smooth scroll

### ISSUE THREAD

**Issue by him-raw99** [DevFeed404/DevFeed-1.0#31]
# Add smooth scroll to your page

The button on the navbar abruptly pulls the the page to subscribe section

I would appreciate if you let me take care of this as a gssoc'23 contributor.

**Comment by ayushgupta4002** [comment]
go ahead @him-raw99

**Comment by him-raw99** [comment]
Thanks for the opportunity @ayushgupta4002 

I did make the scroll smoother but the first time it scrolls all the way down to the testimonials section. This is because of the way you coded the carousel.

**Comment by ayushgupta4002** [comment]
This issue is hereby completed by @him-raw99
