### ISSUE TITLE
want to automate through scripts from root folder

### ISSUE THREAD

**Issue by abhie16** [DevFeed404/DevFeed-1.0#4]
" npm run dev "
will not start the server as there is no script in root folder. Please assign me to write some scripts for automation of the project

**Comment by ayushgupta4002** [comment]
hey @abhie16 
The "npm run dev" command will work if you go to the client folder.
since the server requires env file so it may not start.

**Comment by abhie16** [comment]
Yes I know that , but I would like to write scripts in root folder package.json that it will run from root folder itself without changing directory to the client and we can installl dependencies from root folder itself without changing directories
