### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by kailashchoudhary11** [DevFeed404/DevFeed-1.0#42]
creating a navbar so that the users can easily navigate to various sections such as about and contact.

**Comment by adityavpawar** [comment]
i can solve this issue can you assign me this

**Comment by kailashchoudhary11** [comment]
@ayushgupta4002 Can you assign it to me, so that I can make a PR.

**Comment by ayushgupta4002** [comment]
hey!
I don't think there is any need of elements in navbar in a single page website;
regards
