### ISSUE TITLE
Add back to top button

### ISSUE THREAD

**Issue by suryanshsoni120** [DevFeed404/DevFeed-1.0#49]
If the user wishes to go back to top, it would be better if there is a back-to-top button. I would like to contribute to this issue under GSSOC'23. Please assign me this issue.

**Comment by adityavpawar** [comment]
i can solve this issue can you assign me this issue

**Comment by ayushgupta4002** [comment]
Hi @suryanshsoni120
this issue is already solved in #13 ;
Thanks for your time
