### ISSUE TITLE
To make page responsive

### ISSUE THREAD

**Issue by Somya-Singhal** [DevFeed404/DevFeed-1.0#50]
Hi @ayushgupta4002 
I have noticed that images, testimonials and footer section are not responsive for mobile view.
<img width="621" alt="gssoc2" src="https://github.com/DevFeed404/DevFeed-1.0/assets/88088520/a6bd20a7-3672-42af-be6f-17dc5962a44e">
<img width="622" alt="gssoc3" src="https://github.com/DevFeed404/DevFeed-1.0/assets/88088520/ef74eaa1-498f-4a35-a0cc-9ad6ab853f83">
<img width="626" alt="gssoc4" src="https://github.com/DevFeed404/DevFeed-1.0/assets/88088520/51392b31-8a26-49f1-b72a-73389b9897c7">
It would be better if only one image and testimonial will be shown at a time in mobile instead of showing other half.
Can I work on this issue under GSSoC'23

**Comment by adityavpawar** [comment]
can you assign me this issue.

**Comment by ayushgupta4002** [comment]
hi @Somya-Singhal are you still working on it ?

**Comment by Somya-Singhal** [comment]
> hi @Somya-Singhal are you still working on it ?

yes
