### ISSUE TITLE
Improve Footer Section 

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [DevFeed404/DevFeed-1.0#54]
Hey I am Sneha (MERN stack Developer) I want to improve the footer section and make it attractive Please assign this to me under GSSOC '23
![image](https://github.com/DevFeed404/DevFeed-1.0/assets/94298791/558cde0f-33c9-4fee-94c0-b317b8536741)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by ayushgupta4002** [comment]
hi @i-am-SnehaChauhan 
This issue is similar to #35 
please comment there
