### ISSUE TITLE
[UPDATE] Enhancing Contact Us section with better UI and adding responsive navbar at top

### ISSUE THREAD

**Issue by Mahitej28** [DevFeed404/DevFeed-1.0#61]
Hello!
I am Mahima Churi, a proud contributor at GSSoc'23. I would like to contribute to this project by enhancing the contact us section by adding different contact icons and making it more UI impressive.

Things I would be doing as of now :

📌 Enhancing the Contact Us section by adding some clickable contact icons 
📌Creating a responsive and UI-friendly Navbar
📌Enhancing the Subscribe button by adding animation

Apart from this after solving this issue, I would also like to work on adding a dark theme to the website.

 @ayushgupta4002  If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by Divyansh3021** [comment]
Hey Mahima, you can change the UI of the website. All the best for your contribution. Looking forward to it.

**Comment by Mahitej28** [comment]
Thanks, I will go ahead with it

**Comment by ManasaKaza** [comment]
Hey, I would like to work on this issue under GSSoC

**Comment by Mahitej28** [comment]
I am already woking on this issue kindly look into assigned people and then raise a issue @ManasaKaza

**Comment by Divyansh3021** [comment]
Not yet

**Comment by Mahitej28** [comment]
@Divyansh3021  can u let me know what are your expectations for enhancing the UI of the website, I would work on it then.

**Comment by Divyansh3021** [comment]
The website should remain single paged, the color palette should be elegant and minimalistic and the animations should be used appropriately.

**Comment by Mahitej28** [comment]
Can I add a linear gradient to the website based on the website color theme?
Also, where do you think the website is going bumpy along with the changes I did, let me know so that I would work upon it accordingly
