### ISSUE TITLE
Update the Subscribe Section 

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [DevFeed404/DevFeed-1.0#67]
The Subscribe section is not good enough. It can have good UI. 

![DevFeed Subscribe NEWS](https://github.com/DevFeed404/DevFeed-1.0/assets/94108574/5af600d7-b230-4a82-800c-08bd558a7e8e)

Here left logo can be put in card and right whole thing can be put in a card. Also, the button is not matching with home page. 
Solution : 
1. We can make card type system
2. we can change the color and hovering the button, we can add some style of subscribe button.
3. required can be in email , college, or name.
4. If anyone click in the input section of mail or college or name then already written para inside the box can removed which will be better.

Please Assign me this issue and I will solve that as a GSSoC '23 Contributor.

**Comment by Divyansh3021** [comment]
Hey @Rupantar-Borphukan , I have assigned this issue to you. All the best for your contribution.

**Comment by Rupantar-Borphukan** [comment]
> Hey @Rupantar-Borphukan , I have assigned this issue to you. All the best for your contribution.

Thanks for assigning me the issue.

**Comment by Rupantar-Borphukan** [comment]
Sir, I am not able to done pull request. Can you please help ??
I have done all the changes but in github the pull request button is not
working.
Here is attached screenshot .

**Comment by Rupantar-Borphukan** [comment]
Done Now it working.
Actually initially it was showing some problem and not able to pull request
But now it is working fine.
Thanks for help.
