### ISSUE TITLE
improvement: add responsiveness/css to components for better user experience

### ISSUE THREAD

**Issue by rishuraj1** [DevFeed404/DevFeed-1.0#69]
We might want to add good looking and responsive styles to components such as navbar matching with the theme of the project, for better user experience.

Example: upon hover, button looks like this,
![Screenshot (81)](https://github.com/DevFeed404/DevFeed-1.0/assets/47839626/cbd8e3b6-748d-4b96-8ab2-409c40b2b5cb)

I would really like to contribute to this project, so please can you assign this issue to me. Thanks!
@ayushgupta4002

**Comment by ayushgupta4002** [comment]
that looks good go ahead @rishuraj1

**Comment by rishuraj1** [comment]
@ayushgupta4002  thanks for the opportunity, can you label this issue under GSSoC 23 please as I am a contributor of GSSoC. Thanks.
