### ISSUE TITLE
Addition of socials to the footer

### ISSUE THREAD

**Issue by 007xylogramori** [DevFeed404/DevFeed-1.0#76]
in the footer we can add a github link that redirects the user to this repository and other socials links.
I would like to work on this as a part of Gssoc'23
demo-
![Screenshot (136)](https://github.com/DevFeed404/DevFeed-1.0/assets/119863801/7171acd6-3819-4770-b68d-61ee14593432)

**Comment by Raghucharan16** [comment]
Hey I would Like to work on this can you assign this to me as GSSoC labelled. thank you.
