### ISSUE TITLE
Improve Footer Design to Match Website's Design Scheme

### ISSUE THREAD

**Issue by mahekkg** [DevFeed404/DevFeed-1.0#78]
Hi there! 
As a contributor to **GSSoC'23**, I would like to propose an improvement to the website's footer to make it consistent with the overall design scheme. Currently, the footer appears to be lacking in visual appeal and does not align with the website's style.

**To reproduce:**

Visit the website and scroll down to the footer section.
Observe the design of the footer and compare it with the rest of the website.
Expected Behavior:
The footer should be visually appealing and blend seamlessly with the design scheme of the website. It should enhance the overall user experience and provide important information or navigation links.

**Suggested Changes:**

Update the color scheme of the footer to match the website's primary colors.
Improve the typography and spacing to align with the website's overall styling.
Include relevant links or information that is useful for visitors.
Consider incorporating visual elements or icons that complement the website's design.
By implementing these changes, we can ensure that the footer contributes to a cohesive and visually pleasing user interface.

I am willing to contribute my time and skills to work on improving the footer design as part of my GSSoC'23 contribution. Please let me know if I can be assigned to this task or if there are any specific guidelines or design preferences to consider.

Thank you for considering this improvement.

**Comment by mvpfrever** [comment]
hello sir i can make the more attractive footer please assign this task to me 
GSSOC'23

**Comment by ayushgupta4002** [comment]
hi @mahekkg 
thanks for choosing this project ;
we have a similar issue #35 
please comment there ;
