### ISSUE TITLE
[Feature] Add Star History to the Readme 

### ISSUE THREAD

**Issue by isayakmondal** [DevFeed404/DevFeed-1.0#86]
![image](https://github.com/DevFeed404/DevFeed-1.0/assets/51121313/78db8517-eb76-45bf-b2d6-dcb269cc1d7f)

This would be a good addition to the readme to visualize how the repo has performed.

**Comment by isayakmondal** [comment]
Assign this issue to me

**Comment by Divyansh3021** [comment]
Go ahead @isayakmondal.
