### ISSUE TITLE
Add Preloading Screen 

### ISSUE THREAD

**Issue by SubhamB2003** [DevFeed404/DevFeed-1.0#87]
Hey, Can I add the preloading screen on the website, It's always showing this screen before the actual page is loaded
Here is a demo animation
https://github.com/DevFeed404/DevFeed-1.0/assets/94003231/be7ee74a-78dc-45b7-b532-f1a6478a84d0

I want to work on this feature. Please assign it to me under GSSOC 23.

**Comment by ayushgupta4002** [comment]
go ahead @SubhamB2003 
suggestion : since this project is regarding newsletter try something formal which matches the theme

**Comment by SubhamB2003** [comment]
> go ahead @SubhamB2003 suggestion : since this project is regarding newsletter try something formal which matches the theme

Hey, is this animation ok?

https://github.com/DevFeed404/DevFeed-1.0/assets/94003231/262d0a3f-079b-4483-abb9-914ac56c4449

**Comment by ayushgupta4002** [comment]
yes its look good !! @SubhamB2003
