### ISSUE TITLE
Code Enhancement

### ISSUE THREAD

**Issue by AlfiyaSiddique** [DevFeed404/DevFeed-1.0#94]
## Issue 
The code at some parts of the project can be enhanced by using efficient and proper react methods instead of repeating code lines. For example, in below screenshot 1, we can use the map function instead of repeating lines. Similarly, in screenshot 2, we can use single usestate hook instead of 3 and initialize that single usestate hook with object.

 ## Purpose of this Issue ✨
To enhance the code of the project and follow the DRY principle (Do not Repeat Yourself) Code

## Screenshots
<img width="576" alt="Deskstop" src="https://github.com/DevFeed404/DevFeed-1.0/assets/86224794/60512364-6451-4332-9713-f8d70b24539b">

<img width="445" alt="desktop" src="https://github.com/DevFeed404/DevFeed-1.0/assets/86224794/031d7645-0a4a-40aa-860c-b562ed0d77e1">

## Request
If you think this is worth implementing please assign me this issue under the gssoc'23 label. 🙂

**Comment by Divyansh3021** [comment]
If you think, this will improve the performance of website. Then go ahead @AlfiyaSiddique .
