### ISSUE TITLE
Update of Reach out section and footer section 

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [DevFeed404/DevFeed-1.0#95]
Reach out to us section is simple enough and content is not enough. The footer has nothing except copyright protection line. So, there we can add more icon like facebook, twitter, youtube, etc. and logo of DevFeed at left. 

![Footer section update](https://github.com/DevFeed404/DevFeed-1.0/assets/94108574/f93e6e5a-f07a-4b58-9732-d54f7daf2958)

Please assign me to solve that to make it better UI and proper functionally under GSSoC '23 as a contributor.

**Comment by ayushgupta4002** [comment]
hi @Rupantar-Borphukan 
This issue is similar to #35 
please comment there
